#pragma once
// Generated by configure.py — do not edit manually.
//
// Topology : Hypercube(4)
// Router   : DOR
// Faults   : node=0.05, edge=0.1, seed=42

#include <optional>
#include <random>
#include <string>
#include "Topologies/Hypercube.hpp"
#include "Topologies/CSR.hpp"
#include "Topologies/CSRView.hpp"
#include "Routers/DimensionOrdered.hpp"
#include "Traffic/Rand.hpp"

namespace sim {
  // Topology
  using BaseTopo = topo::Hypercube;
  using CSRTopo  = topo::CSRView<BaseTopo>;

  inline BaseTopo make_topology() { return BaseTopo(4); }

  // Fault injection
  inline constexpr unsigned rng_seed        = 42;
  inline constexpr double   node_fault_prob = 0.05;
  inline constexpr double   edge_fault_prob = 0.1;

  // Config summary for logging
  inline const std::string config_summary =
    "Topology : Hypercube(4)\n"
    "Router   : DOR\n"
    "Faults   : node=0.05, edge=0.1, seed=42";

  // Router
  template <typename T>
  std::optional<typename T::node_type>
  next_hop(const T& topo, const typename T::node_type& cur, const typename T::node_type& dest) {
    return route::hypercube_DOR(topo, cur, dest);
  }

  // Traffic
  template <typename T>
  auto gen_traffic(const T& topo) { return traffic::gen_rand_traffic(topo); }
}
